### ISSUE TITLE
Add 1.19 allay, frogs and tadpoles

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/AggressiveAnimals#1]
**Is your feature request related to a problem? Please describe.**
Frogs and tadpoles were added in MC 1.19.

**Describe the solution you'd like**
Add frogs and tadpoles to configuration and code.

Draft configuration:
```
  allay:
    enabled: false
  frog:
    enabled: false
    speed-multiplier: 1.5
    attack-leap-height: 0.3
  tadpole:
    enabled: false
    attack-leap-height: 0.3
```
