### ISSUE TITLE
Add sniffer to passive mobs

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/AggressiveAnimals#10]
**Is your feature request related to a problem? Please describe.**
New passive mob **sniffer**, added in MC 1.19.4, should be aggression-capable.

**Describe the solution you'd like**
- [x] Add link to default configuration file
```
# Supported MC versions:
# https://github.com/SlimeDog/AggressiveAnimals/wiki
# Default configuration:
# https://github.com/SlimeDog/AggressiveAnimals/blob/master/main/src/main/resources/config.yml
```
- [x] Add sniffer to passive mobs list in configuration
```
mobs:
  sniffer:
    enabled: false
    speed-multiplier: 1.5 // if natural speed is too slow
```
- [x] Implement sniffer aggressiveness
  - ./core/src/main/java/dev/ratas/aggressiveanimals/aggressive/settings/MobType.java
  - ./main/src/test/java/dev/ratas/aggressiveanimals/aggressive/settings/MobTypeSettingSettingsTest.java
