### ISSUE TITLE
Console message constante

### ISSUE THREAD

**Issue by McReiz** [SlimeDog/AggressiveAnimals#28]
**the console sends this message all the time, what does it mean?**
```
[Server] Server thread/WARN [AggressiveAnimals] Unable to unregister mob CHICKEN(20885) (unregister reason UNLOAD_ENTITY) because the mob was not registered
[Server] Server thread/WARN [AggressiveAnimals] Mob is in world 'world' at (-64.39, 63.00, 452.99)
```

**Comment by SlimeDog** [comment]
Please post results of
```
version
version AggressiveAnimals
```

**Comment by McReiz** [comment]
AggressiveAnimals version 1.3.0

Normally we chickens don't touch each other, but this message always comes out when they are close to the players

`# AggressiveAnimals configuration
#
# This file must contain valid YAML code. A YAML checker may be found at http://www.yamllint.com

# Supported MC versions:
# https://github.com/SlimeDog/AggressiveAnimals/wiki
# Default configuration:
# https://github.com/SlimeDog/AggressiveAnimals/blob/master/main/src/main/resources/config.yml
#
# AggressiveAnimals does not rewrite the configuration files if they exist, so changes must be made
# manually.

# ========== CHECK FOR UPDATES =====================================================================
# If you do not want notification of available updates in the console log, you may disable it here.
check-for-updates: true

# ========== BSTATS METRICS ========================================================================
# By default, the plugin collects and transmits anonymous statistics to bstats.org.
# Data collection may be disabled here, or generally in the bStats/config.yml.
#
enable-metrics: true

# ========== DEFAULT ATTACK ATTRIBUTES =============================================================
# These are the default attack attributes, which apply to all mob-types, unless altered individually
# below. You can change them to suit your needs.
# For example, if you want to enable all mob-types, set
#   enabled: true
# If you want all normally passive mob-types to be aggressive, set
#   always-aggressive: true
# Undefined attributes (for example, if you delete them) revert to the in-code default values. Use
#   /aggro info defaults
# display differences between the in-code defaults and configured defaults.
#
defaults:
  enabled: false                   # By default, attacks against players are disabled
  always-aggressive: false         # If false, mobs should attack only in retaliation for player attack
  speed-multiplier: 1.0            # Multiple of vanilla movement speed (examples: 1.0 is regular speed, 0.5 is half speed, 2.0 is double speed)
  attack-damage: 1.0               # Damage inflicted on the target on each attack (in half-hearts)
  attack-damage-limit: 2.0         # The attacker will leave the target alive with the specified amount of health (in half hearts)
  attack-speed: 20.0               # Frequency of attack, same as vanilla except for zombies (in ticks)
  attack-leap-height: 0.0          # Height attacker may leap when attacking (in blocks; 0.0 or below means disabled)
  acquisition-range: 16.0          # Distance at which the attacker can detect a target
  deacquisition-range: 20.0        # Distance at which the victim can escape attack
  attacker-health-threshold: 25.0  # Attack should stop when the health of the attacker falls below the threshold (percentage of full health)
  age:                             # Attacks may be waged by adults and/or babies
    adult: true                    # If true, adult mobs should attack
    baby: false                    # If true, baby mobs should attack
  include-npcs: false              # If true, include NPCs created by NPC managers, such as Citizens, EliteMobs, InfernalMobs, and Shopkeepers
  include-tamed-mobs: true         # If true, include tamed mobs; legal only for tameable mob-types: cat, donkey, fox, horse, llama, mule, parrot, wolf
  include-named-mobs: false        # If true, include named mobs
  override-targeting: false        # If true, remove vanilla targeting behavior and use only attack-conditions; useful for hostile mob-types
  group-aggression-range: 20.0     # If other mobs of the same type are within range of the attacker, they should join the attack (in blocks)
  player-movement:                 # Mob should attack if the player if
    standing: true
    sneaking: true
    walking: true
    sprinting: true
    looking: true                  # Like locking eyes with an Enderman
    sleeping: true
    gliding: true
  enabled-worlds: []               # Worlds in which attacks by this mob-type are enabled; if [], all worlds are enabled
  # - "example-enabled-world"      # To enable specific worlds, delete [] above and add lines like this one, uncommented and replacing the world name
  disabled-worlds: []              # Worlds in which attacks by this mob-type are disabled; if [], no worlds are disabled; takes precedence over enabled_worlds
  # - "example-disabled-world"     # To disable worlds, delete [] above and add lines like this one, uncommented and replacing the world name

# ========== PER-MOB-TYPE ATTACK PROFILES ==========================================================
# These are the per-mob-type attack attributes. All recognized passive and neutral mob-types are
# listed, along with suggested attack attributes. For sanity, no mob-types are enabled by default.
# To enable a specific mob-type, set enabled to true; for example:
# chicken:
#   enabled: true
# Only the enabled attribute is required, but any others may be adjusted by adding appropriate lines
# with different values. Undefined attributes use the default values set above.
#
mobs:
  allay:
    enabled: false
  axolotl:
    enabled: false
    speed-multiplier: 1.05
    attack-leap-height: 0.3
  bee:
    enabled: false
  camel:
    enabled: false
    speed-multiplier: 1.5
  cat:
    enabled: false
    always-aggressive: false
    speed-multiplier: 1.5
    attack-leap-height: 0.3
  cave_spider:
    enabled: false
  chicken:
    enabled: true
    speed-multiplier: 2.25
    attack-damage: 6.0
    acquisition-range: 16.0
    deacquisition-range: 20.0
    override-targeting: true
    group-aggression-range: 20.0
  cod:
    enabled: false
  cow:
    enabled: false
  dolphin:
    enabled: false
  donkey:
    enabled: false
    speed-multiplier: 1.5
  enderman:
    enabled: false
  fox:
    enabled: false
    attack-leap-height: 0.3
  frog:
    enabled: false
    speed-multiplier: 1.5
    attack-leap-height: 0.3
  glow_squid:
    enabled: false
  goat:
    enabled: false
  horse:
    enabled: false
    speed-multiplier: 1.5
  iron_golem:
    enabled: false
  llama:
    enabled: false
    include-tamed-mobs: true   # vanilla behavior
  mooshroom:
    enabled: false
  mule:
    enabled: false
    speed-multiplier: 1.5
  ocelot:
    enabled: false
    attack-leap-height: 0.3
  parrot:
    enabled: false
    speed-multiplier: 1.5
  panda:
    enabled: false
  pig:
    enabled: false
    speed-multiplier: 1.1
  piglin:
    enabled: false
  polar_bear:
    enabled: false
  pufferfish:
    enabled: false
    always-aggressive: true    # vanilla behavior
  rabbit:
    enabled: false
    speed-multiplier: 1.25
    attack-leap-height: 0.3
  salmon:
    enabled: false
  sheep:
    enabled: false
    speed-multiplier: 1.1
  skeleton_horse:
    enabled: false
    speed-multiplier: 1.5
  sniffer:
    enabled: false
    speed-multiplier: 1.5
  snow_golem:
    enabled: false
  spider:
    enabled: false
  squid:
    enabled: false
  strider:
    enabled: false
    speed-multiplier: 1.5
  tadpole:
    enabled: false
    attack-leap-height: 0.3
  trader_llama:
    enabled: false
    include-tamed-mobs: true   # vanilla behavior
  tropical_fish:
    enabled: false
  turtle:
    enabled: false
    speed-multiplier: 1.25
  villager:
    enabled: false
    speed-multiplier: 0.5
  wandering_trader:
    enabled: false
    speed-multiplier: 0.5
  wolf:
    enabled: false
    include-tamed-mobs: true   # vanilla behavior
  zombie_horse:
    enabled: false
  zombified_piglin:
    enabled: false
`

**Comment by McReiz** [comment]
Server version: 
`CraftBukkit version 3610-Spigot-6198b5a-19df23a (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)`

AggressiveAnimals version 1.3.0

Normally we chickens don't touch each other, but this message always comes out when they are close to the players

```
defaults:
  enabled: false                   # By default, attacks against players are disabled
  always-aggressive: false         # If false, mobs should attack only in retaliation for player attack
  speed-multiplier: 1.0            # Multiple of vanilla movement speed (examples: 1.0 is regular speed, 0.5 is half speed, 2.0 is double speed)
  attack-damage: 1.0               # Damage inflicted on the target on each attack (in half-hearts)
  attack-damage-limit: 2.0         # The attacker will leave the target alive with the specified amount of health (in half hearts)
  attack-speed: 20.0               # Frequency of attack, same as vanilla except for zombies (in ticks)
  attack-leap-height: 0.0          # Height attacker may leap when attacking (in blocks; 0.0 or below means disabled)
  acquisition-range: 16.0          # Distance at which the attacker can detect a target
  deacquisition-range: 20.0        # Distance at which the victim can escape attack
  attacker-health-threshold: 25.0  # Attack should stop when the health of the attacker falls below the threshold (percentage of full health)
  age:                             # Attacks may be waged by adults and/or babies
    adult: true                    # If true, adult mobs should attack
    baby: false                    # If true, baby mobs should attack
  include-npcs: false              # If true, include NPCs created by NPC managers, such as Citizens, EliteMobs, InfernalMobs, and Shopkeepers
  include-tamed-mobs: true         # If true, include tamed mobs; legal only for tameable mob-types: cat, donkey, fox, horse, llama, mule, parrot, wolf
  include-named-mobs: false        # If true, include named mobs
  override-targeting: false        # If true, remove vanilla targeting behavior and use only attack-conditions; useful for hostile mob-types
  group-aggression-range: 20.0     # If other mobs of the same type are within range of the attacker, they should join the attack (in blocks)
  player-movement:                 # Mob should attack if the player if
    standing: true
    sneaking: true
    walking: true
    sprinting: true
    looking: true                  # Like locking eyes with an Enderman
    sleeping: true
    gliding: true
  enabled-worlds: []               # Worlds in which attacks by this mob-type are enabled; if [], all worlds are enabled
  # - "example-enabled-world"      # To enable specific worlds, delete [] above and add lines like this one, uncommented and replacing the world name
  disabled-worlds: []              # Worlds in which attacks by this mob-type are disabled; if [], no worlds are disabled; takes precedence over enabled_worlds
  # - "example-disabled-world"     # To disable worlds, delete [] above and add lines like this one, uncommented and replacing the world name

# ========== PER-MOB-TYPE ATTACK PROFILES ==========================================================
# These are the per-mob-type attack attributes. All recognized passive and neutral mob-types are
# listed, along with suggested attack attributes. For sanity, no mob-types are enabled by default.
# To enable a specific mob-type, set enabled to true; for example:
# chicken:
#   enabled: true
# Only the enabled attribute is required, but any others may be adjusted by adding appropriate lines
# with different values. Undefined attributes use the default values set above.
#
mobs:
  allay:
    enabled: false
  axolotl:
    enabled: false
    speed-multiplier: 1.05
    attack-leap-height: 0.3
  bee:
    enabled: false
  camel:
    enabled: false
    speed-multiplier: 1.5
  cat:
    enabled: false
    always-aggressive: false
    speed-multiplier: 1.5
    attack-leap-height: 0.3
  cave_spider:
    enabled: false
  chicken:
    enabled: true
    speed-multiplier: 2.25
    attack-damage: 6.0
    acquisition-range: 16.0
    deacquisition-range: 20.0
    override-targeting: true
    group-aggression-range: 20.0
  cod:
    enabled: false
  cow:
    enabled: false
  dolphin:
    enabled: false
  donkey:
    enabled: false
    speed-multiplier: 1.5
  enderman:
    enabled: false
  fox:
    enabled: false
    attack-leap-height: 0.3
  frog:
    enabled: false
    speed-multiplier: 1.5
    attack-leap-height: 0.3
  glow_squid:
    enabled: false
  goat:
    enabled: false
  horse:
    enabled: false
    speed-multiplier: 1.5
  iron_golem:
    enabled: false
  llama:
    enabled: false
    include-tamed-mobs: true   # vanilla behavior
  mooshroom:
    enabled: false
  mule:
    enabled: false
    speed-multiplier: 1.5
  ocelot:
    enabled: false
    attack-leap-height: 0.3
  parrot:
    enabled: false
    speed-multiplier: 1.5
  panda:
    enabled: false
  pig:
    enabled: false
    speed-multiplier: 1.1
  piglin:
    enabled: false
  polar_bear:
    enabled: false
  pufferfish:
    enabled: false
    always-aggressive: true    # vanilla behavior
  rabbit:
    enabled: false
    speed-multiplier: 1.25
    attack-leap-height: 0.3
  salmon:
    enabled: false
  sheep:
    enabled: false
    speed-multiplier: 1.1
  skeleton_horse:
    enabled: false
    speed-multiplier: 1.5
  sniffer:
    enabled: false
    speed-multiplier: 1.5
  snow_golem:
    enabled: false
  spider:
    enabled: false
  squid:
    enabled: false
  strider:
    enabled: false
    speed-multiplier: 1.5
  tadpole:
    enabled: false
    attack-leap-height: 0.3
  trader_llama:
    enabled: false
    include-tamed-mobs: true   # vanilla behavior
  tropical_fish:
    enabled: false
  turtle:
    enabled: false
    speed-multiplier: 1.25
  villager:
    enabled: false
    speed-multiplier: 0.5
  wandering_trader:
    enabled: false
    speed-multiplier: 0.5
  wolf:
    enabled: false
    include-tamed-mobs: true   # vanilla behavior
  zombie_horse:
    enabled: false
  zombified_piglin:
    enabled: false
```
